apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: backstage-deployment
    app.kubernetes.io/instance: backstage-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: backstage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-demo
  template:
    metadata:
      labels:
        app: backstage-demo
    spec:
      containers:
        - image: 417618740333.dkr.ecr.us-east-2.amazonaws.com/dev-backstage-417618740333-ecr-repository:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-secrets
          name: backstage-demo
          ports:
            - containerPort: 3000
