apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: backstage-service
    app.kubernetes.io/instance: backstage-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: backstage-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: backstage-demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

